### ISSUE TITLE
Enabling minify brokes django-cms toolbar menu

### ISSUE THREAD

**Issue by LennyLip** [adamchainz/django-minify-html#63]
If I enable MinifyHtmlMiddleware then this menu (page, Language) will make broken
<img width="441" alt="Screenshot 2022-09-01 at 08 03 07" src="https://user-images.githubusercontent.com/955994/187835271-b4ea4be4-724e-455b-bd43-fee3ac62bbc4.png">

Not sure what data is cutting off with MinifyHtmlMiddleware is going to this result.

**Comment by adamchainz** [comment]
Hi, without HTML snippets it's impossible to work on a fix. Please provide the before/after HTML of the broken element, from e.g. your browser's "View Source".

Also, we can't really fix HTML issues here, please report them upstream in the minify-html repo: https://github.com/wilsonzlin/minify-html . Ensure you've tested with the latest version first, I know there were some issues fixed in 0.9.0.
